import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./Components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "ByTech",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className + " flex flex-col min-h-screen"}>
                <Header></Header>
                {children}
            </body>
        </html>
    );
}
