import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import firebase from "firebase/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

firebase.initializeApp({
    apiKey: "AIzaSyBHBQuZx4a6yUY2OASwXN3zRgqFdhaquI8",
    authDomain: "dualhacks-ade67.firebaseapp.com",
    projectId: "dualhacks-ade67",
    storageBucket: "dualhacks-ade67.appspot.com",
    messagingSenderId: "1012644923394",
    appId: "1:1012644923394:web:a638049f79696f5b893f1b",
    measurementId: "G-6SFM2338X4",
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
